FROM python:3.7.6-slim-stretch


WORKDIR /usr/src/app

COPY requirements.txt ./

#RUN apt-get -y update
#RUN apt-get -y install build-essential libpq-dev python-dev
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./process_articles.py" ]