version: "3"

services: 
    text-processor-0:
        image: text-processor
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: text-processor-0
    
    text-processor-1:
        image: text-processor
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: text-processor-1
    
    text-processor-2:
        image: text-processor
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: text-processor-2
    
    text-processor-3:
        image: text-processor
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: text-processor-3
    
    # Caddy HTTP сервер, добавлен для
    # ограничения доступа к elasticsearch со стороны внешних программ.
    # Параметры проксирования определены в Caddyfile
    version-store-caddy:
        image: caddy:2.0.0-alpine
        container_name: version-store-caddy
        restart: unless-stopped
        ports:
        - '8080:8080'
        volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./www:/www

# outer network to communicate with other services 
networks:
    default:
        external:
            name: auth_proxy_network